---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[test-kitchen-test]
    attributes:
