dist: xenial
language: ruby

branches:
  only:
    - master

sudo: required

services:
  - docker

install:
  - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current -P chefdk
  - chef exec bundle install

env:
  - SUITE=unit
  - SUITE=default PLATFORM=ubuntu-1804
  - SUITE=default PLATFORM=ubuntu-1604
  - SUITE=default PLATFORM=ubuntu-1404

script:
  - if test "$SUITE" = "unit"; then chef exec delivery local all; fi
  - if test "$SUITE" != "unit"; then chef exec microwave test $SUITE-$PLATFORM; fi

stages:
  - name: test
